version: '3'

services:
  selenium:
    image: selenium/standalone-chrome
    ports:
    - 4444:4444
    restart: always

  app:
    build: 
      context: .
    volumes:
     - ./Tests:/Tests
    command: sh -c "pytest Tests/test_LoginPage.py -v --html=./report.html"
    depends_on:
     - selenium
